#!/bin/bash

# clang-format.sh
#
# Copyright (c) 2023 Mobileye
#
# Licensed under the Apache License, Version 2.0 (the License);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an AS IS BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

format_file() {
  file="${1}"
  if [ -f $file ]; then
    clang-format-6.0 -i ${1}
  fi
}

PARAM1=${1:-HEAD}

case "${PARAM1}" in
  --about )
    echo "Runs clang-format on source files"
    ;;
  * )
    for file in `git diff-index --cached --name-only ${PARAM1} | egrep '\.cl$|\.cpp$|\.c$|\.h$'` ; do
      format_file "${file}"
    done
    ;;
esac

