#!/bin/bash

format_file() {
  file="${1}"
  if [ -f $file ]; then
    clang-format-6.0 -i ${1}
  fi
}

PARAM1=${1:-HEAD}

case "${PARAM1}" in
  --about )
    echo "Runs clang-format on source files"
    ;;
  * )
    for file in `git diff-index --cached --name-only ${PARAM1} | egrep '\.cpp$|\.c$|\.h$' | grep -v '/generated/'` ; do
      format_file "${file}"
    done
    ;;
esac

