#!/bin/bash

# copyright-check.sh
#
# Copyright (c) 2023 Mobileye
#
# Licensed under the Apache License, Version 2.0 (the License);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an AS IS BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# If you update this script for a new date etc then remember to update the
# generate_enum_strings.py script to change its header.

COPYRIGHT2022="Copyright (c) 2022 Mobileye"
COPYRIGHT2023="Copyright (c) 2023 Mobileye"

# Update the copyright message for the changed file
update_file() {
  file="${1}"
  if [ -f $file ]; then
    sed -b -i'' "s/${COPYRIGHT2022}/${COPYRIGHT2023}/" ${file}
  fi
}

# Check that line 4, 5 or 6 contains the correct copyright message.
# This obviously is not a complete check but it captures 99% of cases
check_file() {
  file="${1}"

  if [ -f $file ]; then
    linenumber=$(grep -n "${COPYRIGHT2023}" $file | cut -d : -f 1)

    if [[ "34567" != *"${linenumber}"* ]]; then
      echo "Copyright missing or incorrect in " $file
      exit -1
    fi
  fi
}

PARAM1=${1:-HEAD}

case "${PARAM1}" in
  --about )
    echo "Checks copyright message source files"
    ;;
  * )
    for file in `git diff-index --cached --name-only ${PARAM1} | egrep '\*.ld$|\CMakeLists.txt$|\.cpp$|\.c$|\.h$'` ; do
      update_file "${file}"
      check_file "${file}"
    done
    ;;
esac
