#!/bin/bash

# If you update this script for a new date etc then remember to update the
# generate_enum_strings.py script to change its header.
COPYRIGHT_OLDER="Copyright (c) 202[34]"
COPYRIGHT2025="Copyright (c) 2025"

# Update the copyright message for the changed file
update_file() {
  file="${1}"
  if [ -f $file ]; then
    sed -b -i'' "s/${COPYRIGHT_OLDER}/${COPYRIGHT2025}/" ${file}
  fi
}

exit_code=0

# Check the correct copyright message is contained at all and that it is
# in line the first 15 lines of the file.
# This obviously is not a complete check but it captures 99% of cases
check_file() {
  file="${1}"

  if [ -f $file ]; then
    linenumber=$(grep -n "${COPYRIGHT2025}" $file | cut -d : -f 1)

    if [[ -z "${linenumber}" || "${linenumber}" -gt 15 ]]; then
      echo "Copyright missing or incorrect in " $file
      exit_code=-1
    fi
  fi
}

PARAM1=${1:-HEAD}
case "${PARAM1}" in
  --about )
    echo "Checks copyright message source files"
    ;;
  * )
    for file in `git diff-index --cached --name-only ${PARAM1} | egrep '\.((ld)|(cpp)|(c)|(h)|(S)|(py)|(bazel)|(bzl))$'` ; do
      update_file "${file}"
      check_file "${file}"
    done
	exit $exit_code
    ;;
esac
