#!/bin/sh

# pre-commit
#
# Copyright (c) 2023 Mobileye
#
# Licensed under the Apache License, Version 2.0 (the License);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an AS IS BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# TTL pre-commit hooks

# Use relative paths below. This means that only 1 symlink is required
# in the git hooks directory
SCRIPTS_DIR=`dirname "$0"`/../../scripts/git-hooks

# Apply clang-format to all changed files
# the configuration is in the root of the 
# repo in the .clang-format file
$SCRIPTS_DIR/clang-format

# Finally do a git add to add any files that had changed.
for file in `git diff-index --cached --name-only HEAD | egrep '\*.ld$|\CMakeLists.txt$|\.cpp$|\.c$|\.h$'` ; do
  if [ -f $file ]; then
    git add "${file}"
  fi
done
