var hierarchy =
[
    [ "TTL_sub_tensor< TENSORTYPE >::Origin", "structTTL__sub__tensor_1_1Origin.html", null ],
    [ "TARGET_TYPE", null, [
      [ "StrongTypeConversion< TARGET_TYPE, SOURCE_TYPE, CONVERSION_MULTIPLY, CONVERSION_DIVISION >", "structStrongTypeConversion.html", null ]
    ] ],
    [ "TTL_augmentation", "structTTL__augmentation.html", null ],
    [ "TTL_augmentation_t", "structTTL__augmentation__t.html", null ],
    [ "TTL_common_buffering< TENSORTYPE, BASES_COUNT >", "structTTL__common__buffering.html", null ],
    [ "TTL_const_ext_char_sub_tensor_t", "structTTL__const__ext__char__sub__tensor__t.html", null ],
    [ "TTL_const_ext_char_tensor_t", "structTTL__const__ext__char__tensor__t.html", null ],
    [ "TTL_const_ext_int_sub_tensor_t", "structTTL__const__ext__int__sub__tensor__t.html", null ],
    [ "TTL_const_ext_int_tensor_t", "structTTL__const__ext__int__tensor__t.html", null ],
    [ "TTL_const_ext_long_sub_tensor_t", "structTTL__const__ext__long__sub__tensor__t.html", null ],
    [ "TTL_const_ext_long_tensor_t", "structTTL__const__ext__long__tensor__t.html", null ],
    [ "TTL_const_ext_short_sub_tensor_t", "structTTL__const__ext__short__sub__tensor__t.html", null ],
    [ "TTL_const_ext_short_tensor_t", "structTTL__const__ext__short__tensor__t.html", null ],
    [ "TTL_const_ext_uchar_sub_tensor_t", "structTTL__const__ext__uchar__sub__tensor__t.html", null ],
    [ "TTL_const_ext_uchar_tensor_t", "structTTL__const__ext__uchar__tensor__t.html", null ],
    [ "TTL_const_ext_uint_sub_tensor_t", "structTTL__const__ext__uint__sub__tensor__t.html", null ],
    [ "TTL_const_ext_uint_tensor_t", "structTTL__const__ext__uint__tensor__t.html", null ],
    [ "TTL_const_ext_ulong_sub_tensor_t", "structTTL__const__ext__ulong__sub__tensor__t.html", null ],
    [ "TTL_const_ext_ulong_tensor_t", "structTTL__const__ext__ulong__tensor__t.html", null ],
    [ "TTL_const_ext_ushort_sub_tensor_t", "structTTL__const__ext__ushort__sub__tensor__t.html", null ],
    [ "TTL_const_ext_ushort_tensor_t", "structTTL__const__ext__ushort__tensor__t.html", null ],
    [ "TTL_const_ext_void_sub_tensor_t", "structTTL__const__ext__void__sub__tensor__t.html", null ],
    [ "TTL_const_ext_void_tensor_t", "structTTL__const__ext__void__tensor__t.html", null ],
    [ "TTL_const_int_char_sub_tensor_t", "structTTL__const__int__char__sub__tensor__t.html", null ],
    [ "TTL_const_int_char_tensor_t", "structTTL__const__int__char__tensor__t.html", null ],
    [ "TTL_const_int_int_sub_tensor_t", "structTTL__const__int__int__sub__tensor__t.html", null ],
    [ "TTL_const_int_int_tensor_t", "structTTL__const__int__int__tensor__t.html", null ],
    [ "TTL_const_int_long_sub_tensor_t", "structTTL__const__int__long__sub__tensor__t.html", null ],
    [ "TTL_const_int_long_tensor_t", "structTTL__const__int__long__tensor__t.html", null ],
    [ "TTL_const_int_short_sub_tensor_t", "structTTL__const__int__short__sub__tensor__t.html", null ],
    [ "TTL_const_int_short_tensor_t", "structTTL__const__int__short__tensor__t.html", null ],
    [ "TTL_const_int_uchar_sub_tensor_t", "structTTL__const__int__uchar__sub__tensor__t.html", null ],
    [ "TTL_const_int_uchar_tensor_t", "structTTL__const__int__uchar__tensor__t.html", null ],
    [ "TTL_const_int_uint_sub_tensor_t", "structTTL__const__int__uint__sub__tensor__t.html", null ],
    [ "TTL_const_int_uint_tensor_t", "structTTL__const__int__uint__tensor__t.html", null ],
    [ "TTL_const_int_ulong_sub_tensor_t", "structTTL__const__int__ulong__sub__tensor__t.html", null ],
    [ "TTL_const_int_ulong_tensor_t", "structTTL__const__int__ulong__tensor__t.html", null ],
    [ "TTL_const_int_ushort_sub_tensor_t", "structTTL__const__int__ushort__sub__tensor__t.html", null ],
    [ "TTL_const_int_ushort_tensor_t", "structTTL__const__int__ushort__tensor__t.html", null ],
    [ "TTL_const_int_void_sub_tensor_t", "structTTL__const__int__void__sub__tensor__t.html", null ],
    [ "TTL_const_int_void_tensor_t", "structTTL__const__int__void__tensor__t.html", null ],
    [ "TTL_duplex_buffering< TENSORTYPE >", "structTTL__duplex__buffering.html", null ],
    [ "TTL_duplex_const_char_tensor_buffering_t", "structTTL__duplex__const__char__tensor__buffering__t.html", null ],
    [ "TTL_duplex_const_int_tensor_buffering_t", "structTTL__duplex__const__int__tensor__buffering__t.html", null ],
    [ "TTL_duplex_const_long_tensor_buffering_t", "structTTL__duplex__const__long__tensor__buffering__t.html", null ],
    [ "TTL_duplex_const_short_tensor_buffering_t", "structTTL__duplex__const__short__tensor__buffering__t.html", null ],
    [ "TTL_duplex_const_uchar_tensor_buffering_t", "structTTL__duplex__const__uchar__tensor__buffering__t.html", null ],
    [ "TTL_duplex_const_uint_tensor_buffering_t", "structTTL__duplex__const__uint__tensor__buffering__t.html", null ],
    [ "TTL_duplex_const_ulong_tensor_buffering_t", "structTTL__duplex__const__ulong__tensor__buffering__t.html", null ],
    [ "TTL_duplex_const_ushort_tensor_buffering_t", "structTTL__duplex__const__ushort__tensor__buffering__t.html", null ],
    [ "TTL_duplex_const_void_tensor_buffering_t", "structTTL__duplex__const__void__tensor__buffering__t.html", null ],
    [ "TTL_export_double_buffering< TENSORTYPE >", "structTTL__export__double__buffering.html", null ],
    [ "TTL_export_double_const_char_tensor_buffering_t", "structTTL__export__double__const__char__tensor__buffering__t.html", null ],
    [ "TTL_export_double_const_int_tensor_buffering_t", "structTTL__export__double__const__int__tensor__buffering__t.html", null ],
    [ "TTL_export_double_const_long_tensor_buffering_t", "structTTL__export__double__const__long__tensor__buffering__t.html", null ],
    [ "TTL_export_double_const_short_tensor_buffering_t", "structTTL__export__double__const__short__tensor__buffering__t.html", null ],
    [ "TTL_export_double_const_uchar_tensor_buffering_t", "structTTL__export__double__const__uchar__tensor__buffering__t.html", null ],
    [ "TTL_export_double_const_uint_tensor_buffering_t", "structTTL__export__double__const__uint__tensor__buffering__t.html", null ],
    [ "TTL_export_double_const_ulong_tensor_buffering_t", "structTTL__export__double__const__ulong__tensor__buffering__t.html", null ],
    [ "TTL_export_double_const_ushort_tensor_buffering_t", "structTTL__export__double__const__ushort__tensor__buffering__t.html", null ],
    [ "TTL_export_double_const_void_tensor_buffering_t", "structTTL__export__double__const__void__tensor__buffering__t.html", null ],
    [ "TTL_ext_char_sub_tensor_t", "structTTL__ext__char__sub__tensor__t.html", null ],
    [ "TTL_ext_char_tensor_t", "structTTL__ext__char__tensor__t.html", null ],
    [ "TTL_ext_int_sub_tensor_t", "structTTL__ext__int__sub__tensor__t.html", null ],
    [ "TTL_ext_int_tensor_t", "structTTL__ext__int__tensor__t.html", null ],
    [ "TTL_ext_long_sub_tensor_t", "structTTL__ext__long__sub__tensor__t.html", null ],
    [ "TTL_ext_long_tensor_t", "structTTL__ext__long__tensor__t.html", null ],
    [ "TTL_ext_short_sub_tensor_t", "structTTL__ext__short__sub__tensor__t.html", null ],
    [ "TTL_ext_short_tensor_t", "structTTL__ext__short__tensor__t.html", null ],
    [ "TTL_ext_uchar_sub_tensor_t", "structTTL__ext__uchar__sub__tensor__t.html", null ],
    [ "TTL_ext_uchar_tensor_t", "structTTL__ext__uchar__tensor__t.html", null ],
    [ "TTL_ext_uint_sub_tensor_t", "structTTL__ext__uint__sub__tensor__t.html", null ],
    [ "TTL_ext_uint_tensor_t", "structTTL__ext__uint__tensor__t.html", null ],
    [ "TTL_ext_ulong_sub_tensor_t", "structTTL__ext__ulong__sub__tensor__t.html", null ],
    [ "TTL_ext_ulong_tensor_t", "structTTL__ext__ulong__tensor__t.html", null ],
    [ "TTL_ext_ushort_sub_tensor_t", "structTTL__ext__ushort__sub__tensor__t.html", null ],
    [ "TTL_ext_ushort_tensor_t", "structTTL__ext__ushort__tensor__t.html", null ],
    [ "TTL_ext_void_sub_tensor_t", "structTTL__ext__void__sub__tensor__t.html", null ],
    [ "TTL_ext_void_tensor_t", "structTTL__ext__void__tensor__t.html", null ],
    [ "TTL_import_double_buffering< TENSORTYPE >", "structTTL__import__double__buffering.html", null ],
    [ "TTL_import_double_const_char_tensor_buffering_t", "structTTL__import__double__const__char__tensor__buffering__t.html", null ],
    [ "TTL_import_double_const_int_tensor_buffering_t", "structTTL__import__double__const__int__tensor__buffering__t.html", null ],
    [ "TTL_import_double_const_long_tensor_buffering_t", "structTTL__import__double__const__long__tensor__buffering__t.html", null ],
    [ "TTL_import_double_const_short_tensor_buffering_t", "structTTL__import__double__const__short__tensor__buffering__t.html", null ],
    [ "TTL_import_double_const_uchar_tensor_buffering_t", "structTTL__import__double__const__uchar__tensor__buffering__t.html", null ],
    [ "TTL_import_double_const_uint_tensor_buffering_t", "structTTL__import__double__const__uint__tensor__buffering__t.html", null ],
    [ "TTL_import_double_const_ulong_tensor_buffering_t", "structTTL__import__double__const__ulong__tensor__buffering__t.html", null ],
    [ "TTL_import_double_const_ushort_tensor_buffering_t", "structTTL__import__double__const__ushort__tensor__buffering__t.html", null ],
    [ "TTL_import_double_const_void_tensor_buffering_t", "structTTL__import__double__const__void__tensor__buffering__t.html", null ],
    [ "TTL_int_char_sub_tensor_t", "structTTL__int__char__sub__tensor__t.html", null ],
    [ "TTL_int_char_tensor_t", "structTTL__int__char__tensor__t.html", null ],
    [ "TTL_int_int_sub_tensor_t", "structTTL__int__int__sub__tensor__t.html", null ],
    [ "TTL_int_int_tensor_t", "structTTL__int__int__tensor__t.html", null ],
    [ "TTL_int_long_sub_tensor_t", "structTTL__int__long__sub__tensor__t.html", null ],
    [ "TTL_int_long_tensor_t", "structTTL__int__long__tensor__t.html", null ],
    [ "TTL_int_short_sub_tensor_t", "structTTL__int__short__sub__tensor__t.html", null ],
    [ "TTL_int_short_tensor_t", "structTTL__int__short__tensor__t.html", null ],
    [ "TTL_int_uchar_sub_tensor_t", "structTTL__int__uchar__sub__tensor__t.html", null ],
    [ "TTL_int_uchar_tensor_t", "structTTL__int__uchar__tensor__t.html", null ],
    [ "TTL_int_uint_sub_tensor_t", "structTTL__int__uint__sub__tensor__t.html", null ],
    [ "TTL_int_uint_tensor_t", "structTTL__int__uint__tensor__t.html", null ],
    [ "TTL_int_ulong_sub_tensor_t", "structTTL__int__ulong__sub__tensor__t.html", null ],
    [ "TTL_int_ulong_tensor_t", "structTTL__int__ulong__tensor__t.html", null ],
    [ "TTL_int_ushort_sub_tensor_t", "structTTL__int__ushort__sub__tensor__t.html", null ],
    [ "TTL_int_ushort_tensor_t", "structTTL__int__ushort__tensor__t.html", null ],
    [ "TTL_int_void_sub_tensor_t", "structTTL__int__void__sub__tensor__t.html", null ],
    [ "TTL_int_void_tensor_t", "structTTL__int__void__tensor__t.html", null ],
    [ "TTL_io_char_tensor_t", "structTTL__io__char__tensor__t.html", null ],
    [ "TTL_io_int_tensor_t", "structTTL__io__int__tensor__t.html", null ],
    [ "TTL_io_long_tensor_t", "structTTL__io__long__tensor__t.html", null ],
    [ "TTL_io_short_tensor_t", "structTTL__io__short__tensor__t.html", null ],
    [ "TTL_io_tensors< TENSORTYPE >", "structTTL__io__tensors.html", null ],
    [ "TTL_io_uchar_tensor_t", "structTTL__io__uchar__tensor__t.html", null ],
    [ "TTL_io_uint_tensor_t", "structTTL__io__uint__tensor__t.html", null ],
    [ "TTL_io_ulong_tensor_t", "structTTL__io__ulong__tensor__t.html", null ],
    [ "TTL_io_ushort_tensor_t", "structTTL__io__ushort__tensor__t.html", null ],
    [ "TTL_io_void_tensor_t", "structTTL__io__void__tensor__t.html", null ],
    [ "TTL_layout", "structTTL__layout.html", null ],
    [ "TTL_layout_t", "structTTL__layout__t.html", null ],
    [ "TTL_offset", "structTTL__offset.html", null ],
    [ "TTL_offset_t", "structTTL__offset__t.html", null ],
    [ "TTL_overlap", "structTTL__overlap.html", null ],
    [ "TTL_overlap_t", "structTTL__overlap__t.html", null ],
    [ "TTL_shape", "structTTL__shape.html", null ],
    [ "TTL_shape_t", "structTTL__shape__t.html", null ],
    [ "TTL_simplex_buffering< TENSORTYPE >", "structTTL__simplex__buffering.html", null ],
    [ "TTL_simplex_const_char_tensor_buffering_t", "structTTL__simplex__const__char__tensor__buffering__t.html", null ],
    [ "TTL_simplex_const_int_tensor_buffering_t", "structTTL__simplex__const__int__tensor__buffering__t.html", null ],
    [ "TTL_simplex_const_long_tensor_buffering_t", "structTTL__simplex__const__long__tensor__buffering__t.html", null ],
    [ "TTL_simplex_const_short_tensor_buffering_t", "structTTL__simplex__const__short__tensor__buffering__t.html", null ],
    [ "TTL_simplex_const_uchar_tensor_buffering_t", "structTTL__simplex__const__uchar__tensor__buffering__t.html", null ],
    [ "TTL_simplex_const_uint_tensor_buffering_t", "structTTL__simplex__const__uint__tensor__buffering__t.html", null ],
    [ "TTL_simplex_const_ulong_tensor_buffering_t", "structTTL__simplex__const__ulong__tensor__buffering__t.html", null ],
    [ "TTL_simplex_const_ushort_tensor_buffering_t", "structTTL__simplex__const__ushort__tensor__buffering__t.html", null ],
    [ "TTL_simplex_const_void_tensor_buffering_t", "structTTL__simplex__const__void__tensor__buffering__t.html", null ],
    [ "TTL_StrongType< T, UNIQUE_ENUM_CLASS >", "structTTL__StrongType.html", null ],
    [ "TTL_sub_tensor< TENSORTYPE >", "structTTL__sub__tensor.html", null ],
    [ "TTL_tensor< TENSORTYPE >", "structTTL__tensor.html", null ],
    [ "TTL_tile", "structTTL__tile.html", null ],
    [ "TTL_tile_t", "structTTL__tile__t.html", null ],
    [ "TTL_tiler", "structTTL__tiler.html", null ],
    [ "TTL_tiler_t", "structTTL__tiler__t.html", null ]
];