name: GitHub Actions Build and Deploy Documentation
run-name: ${{ github.actor }} is building and deploying Doxygen
on: [push]
jobs:
    build-and-deploy-documentation:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Build Info
              run: |
                  echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
                  echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
                  echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
            - name: Check out repository code
              uses: actions/checkout@v4
            - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
            - run: echo "💡 Building Doxygen."
            - name: Build Doxygen
              uses: mattnotmitt/doxygen-action@v1.9.4
              with:
                  working-directory: .
                  doxyfile-path: scripts/doxyfile.in
            - name: Build Docs
              run: cd docs && pip install -r requirements.txt && make html && rm -rf ../gh-pages/docs && mv _build/html ../gh-pages/docs

            - if: github.ref == 'refs/heads/main'
              name: Deploy Doxygen
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: gh-pages
                  single-commit: true

            - run: echo "🍏 This job's status is ${{ job.status }}."
